# _config.yml
title: Foam
plugins:
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter
# The default Jekyll theme we will be using
theme: jekyll-theme-primer
repository: goldfishlaser/dev-notes
permalink: pretty
